---
kind: pipeline
name: docker

trigger:
  branch:
    - dev

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
      
workspace:
  path: /go/src/github.com/open-beagle/gpustack

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
        - ./.venv
      endpoint: https://cache.ali.wodcloud.com
      access_key:
        from_secret: S3_ACCESS_KEY_ALIYUN
      secret_key:
        from_secret: S3_SECRET_KEY_ALIYUN

  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: python
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/python:3.10-bookworm
    environment:
      VERSION: v0.3.2
      POETRY_PYPI_MIRROR_INDEX: https://pypi.tuna.tsinghua.edu.cn/simple/
    commands:
      - bash .beagle/build.sh

  - name: docker-cuda
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cuda:12.4.1-py310
      dockerfile: .beagle/cuda.dockerfile
      repo: wod/gpustack
      version: "v0.3.2-cuda"
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-cann
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:8.0.RC3-py310-kernel910b
      dockerfile: .beagle/cann.dockerfile
      repo: wod/gpustack
      version: "v0.3.2-cann"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_ACCESS_KEY_ALIYUN
get:
  name: S3_ACCESS_KEY_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_SECRET_KEY_ALIYUN
get:
  name: S3_SECRET_KEY_ALIYUN
  path: devops-secrets
