---
kind: pipeline
name: docker

trigger:
  branch:
    - dev-v0.7.0

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/open-beagle/gpustack

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
        - ./.venv
      endpoint: https://cache.ali.wodcloud.com
      access_key:
        from_secret: S3_ACCESS_KEY_ALIYUN
      secret_key:
        from_secret: S3_SECRET_KEY_ALIYUN

  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: python
    image: registry.cn-qingdao.aliyuncs.com/wod/python:3.12.3-amd64
    environment:
      VERSION: v0.7.0
      POETRY_PYPI_MIRROR_INDEX: https://pypi.tuna.tsinghua.edu.cn/simple/
    commands:
      - bash .beagle/build.sh

  - name: docker-cuda
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cuda:12.5.1-runtime-ubuntu22.04
      dockerfile: .beagle/cuda.dockerfile
      repo: wod/gpustack
      version: "v0.7.0-cuda"
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-cann
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:8.0.RC3.alpha003-kernel910b-py310
      dockerfile: .beagle/cann.dockerfile
      repo: wod/gpustack
      version: "v0.7.0-cann"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-musa
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/musa:rc4.2.0-runtime-ubuntu-amd64
      dockerfile: .beagle/musa.dockerfile
      repo: wod/gpustack
      version: "v0.7.0-musa"
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: docker-arm64

trigger:
  branch:
    - dev-arm64

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/open-beagle/gpustack

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
        - ./.venv
      endpoint: https://cache.ali.wodcloud.com
      access_key:
        from_secret: S3_ACCESS_KEY_ALIYUN
      secret_key:
        from_secret: S3_SECRET_KEY_ALIYUN

  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: python
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/python:3.10-bookworm
    environment:
      VERSION: v0.7.0
      POETRY_PYPI_MIRROR_INDEX: https://pypi.tuna.tsinghua.edu.cn/simple/
    commands:
    commands:
      - bash .beagle/build.sh
      - git apply .beagle/v0.7.0-s3-project.patch

  - name: docker-cann-kernel
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:8.0.RC3.alpha003-kernel910b-py310
      dockerfile: .beagle/cann.dockerfile
      repo: wod/gpustack
      version: "v0.7.0-cann8.0.RC3.alpha003-kernel910b"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
---
kind: pipeline
name: docker-cann-8.0.RC3.beta1

trigger:
  branch:
    - dev-cann-8.0.RC3.beta1

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/open-beagle/gpustack

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
        - ./.venv
      endpoint: https://cache.ali.wodcloud.com
      access_key:
        from_secret: S3_ACCESS_KEY_ALIYUN
      secret_key:
        from_secret: S3_SECRET_KEY_ALIYUN

  - name: fetch
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: python
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/python:3.10-bookworm
    environment:
      VERSION: v0.7.0
      POETRY_PYPI_MIRROR_INDEX: https://pypi.tuna.tsinghua.edu.cn/simple/
    commands:
      - bash .beagle/build.sh

  - name: docker-cann
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry-vpc.cn-qingdao.aliyuncs.com/wod/cann:8.0.RC3.beta1-kernel910b-py310
      dockerfile: .beagle/cann.dockerfile
      repo: wod/gpustack
      version: "v0.7.0-cann-8.0.RC3.beta1-kernel910b"
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
        
---
kind: pipeline
name: harbor

trigger:
  branch:
    - release-v0.7

clone:
  disable: true

steps:
  - name: harbor-cuda
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry-vpc.cn-qingdao.aliyuncs.com/wod/gpustack:v0.7.0-cuda
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/gpustack:v0.7-cuda
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-cann
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry-vpc.cn-qingdao.aliyuncs.com/wod/gpustack:v0.7.0-cann
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/gpustack:v0.7-cann
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-musa
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    settings:
      source: registry-vpc.cn-qingdao.aliyuncs.com/wod/gpustack:v0.7.0-musa
      target: registry-vpc.cn-qingdao.aliyuncs.com/wod/gpustack:v0.7-musa
      registry: registry-vpc.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
        
---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_ACCESS_KEY_ALIYUN
get:
  name: S3_ACCESS_KEY_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_SECRET_KEY_ALIYUN
get:
  name: S3_SECRET_KEY_ALIYUN
  path: devops-secrets
